pages:
  image: ruby:2.7
  stage: deploy
  script:
  - cd docs
  - bundle install
  - bundle exec jekyll build -d ../public
  artifacts:
    paths:
    - public

install:
  image: python:3.6 
  script:
  - pip install packaging jupyter
  - pip install -e .

