default:
  image: python:3.6 


install: 
  script:
  - pip install nbdev jupyter
  - pip install -e .

read_notebooks:
  script:
  - nbdev_read_nbs

 
pages:
  image: ruby:2.7
  stage: deploy
  script:
  - cd docs
  - bundle install
  - bundle exec jekyll build -d ../public
  artifacts:
    paths:
    - public

 
